#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'runit', '~> 1.6.0'
cookbook 'nginx', '~> 2.7.6'
cookbook 'redisio', '~> 2.3.0'
cookbook 'postgresql', '~> 3.4.20'
cookbook 'beanstalkd', '~> 0.1.5'
cookbook 'rbenv', '~> 1.7.1'
cookbook 'nodejs', '~> 2.4.2'
cookbook 'database', '~> 4.0.6'
cookbook 'python', '~> 1.4.6'
cookbook 'ntp', '~> 1.8.6'
cookbook 'latest-git', :git => 'https://github.com/aspyatkin/latest-git.git', :ref => 'v1.0.0'
